# Generated by Django 5.2 on 2025-05-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='about_me',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
