# Generated by Django 5.2 on 2025-06-09 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_owner_about_me_alter_owner_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_blob', models.BinaryField(default=bytes)),
                ('content_type', models.CharField(default='', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_blob', to='owner.owner')),
            ],
        ),
    ]
