# Generated by Django 5.2 on 2025-05-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='about_me',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='job',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
