# Generated by Django 5.2 on 2025-06-09 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_alter_tenant_about_me_alter_tenant_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_blob', models.BinaryField(default=bytes)),
                ('content_type', models.CharField(default='', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_blob', to='tenant.tenant')),
            ],
        ),
    ]
