# Generated by Django 5.2 on 2025-06-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immobile', '0002_delete_rental'),
        ('immobile', '0003_initial'),
    ]

    operations = [
    ]
